global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spark'
    static_configs:
      - targets: ['spark-master:8080']
    metrics_path: /metrics

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: /metrics

  - job_name: 'tensorflow-serving'
    static_configs:
      - targets: ['tensorflow-serving:9090']
    metrics_path: /monitoring/prometheus/metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']